### ISSUE TITLE
How does gap_ratio works?

### ISSUE THREAD

**Issue by orbitaloop** [twardoch/audiostretchy#1]
Hi,
First of all, thank you so much for your work, your lib is super useful for my project with ElevenLabs.

I can't wrap my head on the gap_ratio parameters. If I understand well, it's to increase the silence length in audio, isn't it?
So if I want to slow down a speech by 30% and increase the silence length by 2 (or 100%) I would use this command:
`audiostretchy tests_audio.wav test_audio-1.3.wav -r 1.3 -g 2`
But it doesn't seem to increase the silence. I feel I'm missing something...
Thanks for your help!

**Comment by twardoch** [comment]
It should work like that, yes
